nickname: Yachiyo

prompt:
  system: <dir-to-system-prompt>

gateway:
  onebot:
    enabled: True
    port: 16801
  client:
    enabled: True
    port: 16802

initiative:
  threshold: 0.9
  factors:
    sociability: 
      curve:  0.8
      value:  0.8
      max:    1
      weight: 1
    alonetime:
      curve:  1/(1+e^(-x+3))
      value:  0
      max:    10
      weight: 2
    daytime:
      curve:  sin((π/12)*(x+14))+0.5
      value:  0
      max:    24
      weight: 2

llm:
  default: deepseek
  providers:
    - enabled: True
      name: deepseek
      base_url: https://api.deepseek.com
      secret: <your-key-here>
      model: deepseek-v4-pro
      
    - enabled: True
      name: qwen3.7-plus
      base_url: <your-base-url-here>
      secret: <your-key-here>
      model: qwen3.7-plus
