version: 3

tasks:
  server:build:
    desc: Build Yachiyo server
    silent: true
    cmds:
      - mkdir -p build/server
      - go build -trimpath -o build/server/server{{exeExt}} yachiyo-runtime/server.go
      - cp README.md build/server
      - cp LICENSE build/server
      - cp -r assets/* build/server
      
  server:
    desc: Build and run Yachiyo server
    silent: true
    cmds:
      - task: server:build
      - cd build/server && ./server{{exeExt}}

  cli:build:
    desc: Build Yachiyo CLI
    silent: true
    cmds:
      - mkdir -p build/cli
      - go build -trimpath -o build/cli/client{{exeExt}} yachiyo-client/cli/main.go

  cli:
    desc: Build and run Yachiyo CLI
    silent: true
    cmds:
      - task: cli:build
      - cd build/server && ./client{{exeExt}}
  
  pancake:
    desc: Build Pancake
    dir: yachiyo-client/pancake
    silent: true
    cmds:
      - flutter pub get
      - flutter build {{.CLI_ARGS}}
  
  pancake:release:
    desc: Build Pancake (Release)
    dir: yachiyo-client/pancake
    silent: true
    cmds:
      - flutter pub get
      - flutter build {{.CLI_ARGS}} --release