version: 3

tasks:
  serverdev:
    desc: build and run Yachiyo server (Windows) # development
    silent: true
    cmds:
      - mkdir -p build/server
      - go build -o build/server/server.exe yachiyo-runtime/server.go
      - cp config.example.yaml ./build/server
      - cp README.md build/server
      - cp LICENSE build/server
      - mkdir -p build/server/prompt
      
      # running server
      - cd build/server && server.exe

  clidev:
    desc: build and run Yachiyo CLI (Windows) # development
    silent: true
    cmds:
      - mkdir -p build/cli
      - go build -o build/cli/client.exe yachiyo-client/cli/main.go

      # running CLI
      - cd build/cli && client.exe