version: 3

env:
  YACHIYO_GLOBAL_MODE: production # Default mode is production, and can be overridden by tasks.
  YACHIYO_CHAR_PATH: ./yachiyo-dev/package.yachiyo/prompts # Default character data path, consuming being under development.

tasks:
  dev:
    desc: Run Yachiyo Server in development mode
    silent: true
    env:
      YACHIYO_GLOBAL_MODE: development
      YACHIYO_CHAR_PATH: "{{.USER_WORKING_DIR}}/yachiyo-dev/package.yachiyo/prompts"
    dir: ./yachiyo-server
    cmds:
      - "echo [Yachiyo] Running Yachiyo Server in $YACHIYO_GLOBAL_MODE mode"
      - "echo [Yachiyo] Using character data from $YACHIYO_CHAR_PATH"
      - go run main.go