syntax = "proto3";
package yachiyo.chat;

option go_package = "yachiyo/yachiyo-core/chat";

service ChatService {
    rpc CreateSession(CreateSessionRequest) returns (CreateSessionResponse);
    rpc ChatStream(ChatRequest) returns (stream ChatResponse);
}

message CreateSessionRequest{

}

message CreateSessionResponse {
    string uuid = 1;
}

message Message {
    int64 id = 1;
    string uuid = 2;
    string session_id = 3;
    string role = 4;
    string content = 5;
    int64 timestamp = 6;
}

message ChatRequest {
    string session_id = 1;
    string model = 2;
    string content = 3;
}

message ChatResponse {
    string id = 1;
    Message delta = 2;
}
