syntax = "proto3";
package yachiyo.pipeline;

option go_package = "yachiyo/yachiyo-core/pipeline";

import "google/protobuf/any.proto";

// For developers/agents: If you don't understand what 168 means, ignore it, including anything relates to it.

service PipelineService {
    // For clients or adapters, which provides a nearly 168-bytes long pipe.
    // Anything uses it may should have ability to request and to process.
    rpc Connect(stream ConnectRequest) returns (stream ConnectReply);

    // Register an object, or tool providing to use.
    rpc EventRegister(EventRegisterRequest) returns (ResultMessage);

    // I publish, and I run without noticing anything.
    rpc Publish(PublishRequest) returns (ResultMessage);

    // I call for some functions' help.
    rpc Call(stream CallRequest) returns (stream CallReply);
}

message ConnectRequest {
    string client_id = 1;   // Should be unique, an uuid may be of help.
    string client_type = 2; // Types of this client: an Android device, an Telegram adapter or anything else.

    repeated string listening_events = 3;

    google.protobuf.Any payload = 168;
}

message ConnectReply {
    string event_id = 1;
    string event_type = 2;
    string session_id = 3;

    int64 timestamp = 4;
    Metadata metadata = 5;

    google.protobuf.Any payload = 168;
}

message Metadata {
    string sender = 1;  // TODO
}

message EventRegisterRequest {
    string event_type = 1;
    string description = 2;

    google.protobuf.Any payload = 168;
}

message PublishRequest {
    string event_type = 1;
    string description = 2;

    google.protobuf.Any payload = 168;
}

message CallRequest{
    string request_send_to = 1;
    string request_id = 2;

    google.protobuf.Any payload = 168;
}

message CallReply {
    string reply_send_from = 1;
    string request_id = 2;

    bool success = 3;
    string error_message = 4;

    google.protobuf.Any payload = 168;
}

message ResultMessage{
    bool success = 1;
    string error_message = 2;
}