// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: pipeline.proto

package pipeline

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ClientId        string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`       // Should be unique, an uuid may be of help.
	ClientType      string                 `protobuf:"bytes,2,opt,name=client_type,json=clientType,proto3" json:"client_type,omitempty"` // Types of this client: an Android device, an Telegram adapter or anything else.
	ListeningEvents []string               `protobuf:"bytes,3,rep,name=listening_events,json=listeningEvents,proto3" json:"listening_events,omitempty"`
	Payload         *anypb.Any             `protobuf:"bytes,168,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_pipeline_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pipeline_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_pipeline_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ConnectRequest) GetClientType() string {
	if x != nil {
		return x.ClientType
	}
	return ""
}

func (x *ConnectRequest) GetListeningEvents() []string {
	if x != nil {
		return x.ListeningEvents
	}
	return nil
}

func (x *ConnectRequest) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ConnectReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata      *Metadata              `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Payload       *anypb.Any             `protobuf:"bytes,168,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectReply) Reset() {
	*x = ConnectReply{}
	mi := &file_pipeline_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectReply) ProtoMessage() {}

func (x *ConnectReply) ProtoReflect() protoreflect.Message {
	mi := &file_pipeline_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectReply.ProtoReflect.Descriptor instead.
func (*ConnectReply) Descriptor() ([]byte, []int) {
	return file_pipeline_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectReply) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *ConnectReply) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *ConnectReply) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ConnectReply) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ConnectReply) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ConnectReply) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"` // TODO
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_pipeline_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_pipeline_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_pipeline_proto_rawDescGZIP(), []int{2}
}

func (x *Metadata) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

type EventRegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Payload       *anypb.Any             `protobuf:"bytes,168,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventRegisterRequest) Reset() {
	*x = EventRegisterRequest{}
	mi := &file_pipeline_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventRegisterRequest) ProtoMessage() {}

func (x *EventRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pipeline_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventRegisterRequest.ProtoReflect.Descriptor instead.
func (*EventRegisterRequest) Descriptor() ([]byte, []int) {
	return file_pipeline_proto_rawDescGZIP(), []int{3}
}

func (x *EventRegisterRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EventRegisterRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EventRegisterRequest) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventType     string                 `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Payload       *anypb.Any             `protobuf:"bytes,168,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_pipeline_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pipeline_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_pipeline_proto_rawDescGZIP(), []int{4}
}

func (x *PublishRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *PublishRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PublishRequest) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

type CallRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestSendTo string                 `protobuf:"bytes,1,opt,name=request_send_to,json=requestSendTo,proto3" json:"request_send_to,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Payload       *anypb.Any             `protobuf:"bytes,168,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallRequest) Reset() {
	*x = CallRequest{}
	mi := &file_pipeline_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallRequest) ProtoMessage() {}

func (x *CallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pipeline_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallRequest.ProtoReflect.Descriptor instead.
func (*CallRequest) Descriptor() ([]byte, []int) {
	return file_pipeline_proto_rawDescGZIP(), []int{5}
}

func (x *CallRequest) GetRequestSendTo() string {
	if x != nil {
		return x.RequestSendTo
	}
	return ""
}

func (x *CallRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CallRequest) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

type CallReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplySendFrom string                 `protobuf:"bytes,1,opt,name=reply_send_from,json=replySendFrom,proto3" json:"reply_send_from,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Payload       *anypb.Any             `protobuf:"bytes,168,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallReply) Reset() {
	*x = CallReply{}
	mi := &file_pipeline_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallReply) ProtoMessage() {}

func (x *CallReply) ProtoReflect() protoreflect.Message {
	mi := &file_pipeline_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallReply.ProtoReflect.Descriptor instead.
func (*CallReply) Descriptor() ([]byte, []int) {
	return file_pipeline_proto_rawDescGZIP(), []int{6}
}

func (x *CallReply) GetReplySendFrom() string {
	if x != nil {
		return x.ReplySendFrom
	}
	return ""
}

func (x *CallReply) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CallReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CallReply) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *CallReply) GetPayload() *anypb.Any {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ResultMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultMessage) Reset() {
	*x = ResultMessage{}
	mi := &file_pipeline_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultMessage) ProtoMessage() {}

func (x *ResultMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pipeline_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultMessage.ProtoReflect.Descriptor instead.
func (*ResultMessage) Descriptor() ([]byte, []int) {
	return file_pipeline_proto_rawDescGZIP(), []int{7}
}

func (x *ResultMessage) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResultMessage) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_pipeline_proto protoreflect.FileDescriptor

const file_pipeline_proto_rawDesc = "" +
	"\n" +
	"\x0epipeline.proto\x12\x10yachiyo.pipeline\x1a\x19google/protobuf/any.proto\"\xaa\x01\n" +
	"\x0eConnectRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1f\n" +
	"\vclient_type\x18\x02 \x01(\tR\n" +
	"clientType\x12)\n" +
	"\x10listening_events\x18\x03 \x03(\tR\x0flisteningEvents\x12/\n" +
	"\apayload\x18\xa8\x01 \x01(\v2\x14.google.protobuf.AnyR\apayload\"\xee\x01\n" +
	"\fConnectReply\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x126\n" +
	"\bmetadata\x18\x05 \x01(\v2\x1a.yachiyo.pipeline.MetadataR\bmetadata\x12/\n" +
	"\apayload\x18\xa8\x01 \x01(\v2\x14.google.protobuf.AnyR\apayload\"\"\n" +
	"\bMetadata\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\"\x88\x01\n" +
	"\x14EventRegisterRequest\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12/\n" +
	"\apayload\x18\xa8\x01 \x01(\v2\x14.google.protobuf.AnyR\apayload\"\x82\x01\n" +
	"\x0ePublishRequest\x12\x1d\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tR\teventType\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12/\n" +
	"\apayload\x18\xa8\x01 \x01(\v2\x14.google.protobuf.AnyR\apayload\"\x85\x01\n" +
	"\vCallRequest\x12&\n" +
	"\x0frequest_send_to\x18\x01 \x01(\tR\rrequestSendTo\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12/\n" +
	"\apayload\x18\xa8\x01 \x01(\v2\x14.google.protobuf.AnyR\apayload\"\xc2\x01\n" +
	"\tCallReply\x12&\n" +
	"\x0freply_send_from\x18\x01 \x01(\tR\rreplySendFrom\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12/\n" +
	"\apayload\x18\xa8\x01 \x01(\v2\x14.google.protobuf.AnyR\apayload\"N\n" +
	"\rResultMessage\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage2\xd2\x02\n" +
	"\x0fPipelineService\x12O\n" +
	"\aConnect\x12 .yachiyo.pipeline.ConnectRequest\x1a\x1e.yachiyo.pipeline.ConnectReply(\x010\x01\x12X\n" +
	"\rEventRegister\x12&.yachiyo.pipeline.EventRegisterRequest\x1a\x1f.yachiyo.pipeline.ResultMessage\x12L\n" +
	"\aPublish\x12 .yachiyo.pipeline.PublishRequest\x1a\x1f.yachiyo.pipeline.ResultMessage\x12F\n" +
	"\x04Call\x12\x1d.yachiyo.pipeline.CallRequest\x1a\x1b.yachiyo.pipeline.CallReply(\x010\x01B\x1fZ\x1dyachiyo/yachiyo-core/pipelineb\x06proto3"

var (
	file_pipeline_proto_rawDescOnce sync.Once
	file_pipeline_proto_rawDescData []byte
)

func file_pipeline_proto_rawDescGZIP() []byte {
	file_pipeline_proto_rawDescOnce.Do(func() {
		file_pipeline_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pipeline_proto_rawDesc), len(file_pipeline_proto_rawDesc)))
	})
	return file_pipeline_proto_rawDescData
}

var file_pipeline_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pipeline_proto_goTypes = []any{
	(*ConnectRequest)(nil),       // 0: yachiyo.pipeline.ConnectRequest
	(*ConnectReply)(nil),         // 1: yachiyo.pipeline.ConnectReply
	(*Metadata)(nil),             // 2: yachiyo.pipeline.Metadata
	(*EventRegisterRequest)(nil), // 3: yachiyo.pipeline.EventRegisterRequest
	(*PublishRequest)(nil),       // 4: yachiyo.pipeline.PublishRequest
	(*CallRequest)(nil),          // 5: yachiyo.pipeline.CallRequest
	(*CallReply)(nil),            // 6: yachiyo.pipeline.CallReply
	(*ResultMessage)(nil),        // 7: yachiyo.pipeline.ResultMessage
	(*anypb.Any)(nil),            // 8: google.protobuf.Any
}
var file_pipeline_proto_depIdxs = []int32{
	8,  // 0: yachiyo.pipeline.ConnectRequest.payload:type_name -> google.protobuf.Any
	2,  // 1: yachiyo.pipeline.ConnectReply.metadata:type_name -> yachiyo.pipeline.Metadata
	8,  // 2: yachiyo.pipeline.ConnectReply.payload:type_name -> google.protobuf.Any
	8,  // 3: yachiyo.pipeline.EventRegisterRequest.payload:type_name -> google.protobuf.Any
	8,  // 4: yachiyo.pipeline.PublishRequest.payload:type_name -> google.protobuf.Any
	8,  // 5: yachiyo.pipeline.CallRequest.payload:type_name -> google.protobuf.Any
	8,  // 6: yachiyo.pipeline.CallReply.payload:type_name -> google.protobuf.Any
	0,  // 7: yachiyo.pipeline.PipelineService.Connect:input_type -> yachiyo.pipeline.ConnectRequest
	3,  // 8: yachiyo.pipeline.PipelineService.EventRegister:input_type -> yachiyo.pipeline.EventRegisterRequest
	4,  // 9: yachiyo.pipeline.PipelineService.Publish:input_type -> yachiyo.pipeline.PublishRequest
	5,  // 10: yachiyo.pipeline.PipelineService.Call:input_type -> yachiyo.pipeline.CallRequest
	1,  // 11: yachiyo.pipeline.PipelineService.Connect:output_type -> yachiyo.pipeline.ConnectReply
	7,  // 12: yachiyo.pipeline.PipelineService.EventRegister:output_type -> yachiyo.pipeline.ResultMessage
	7,  // 13: yachiyo.pipeline.PipelineService.Publish:output_type -> yachiyo.pipeline.ResultMessage
	6,  // 14: yachiyo.pipeline.PipelineService.Call:output_type -> yachiyo.pipeline.CallReply
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_pipeline_proto_init() }
func file_pipeline_proto_init() {
	if File_pipeline_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pipeline_proto_rawDesc), len(file_pipeline_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pipeline_proto_goTypes,
		DependencyIndexes: file_pipeline_proto_depIdxs,
		MessageInfos:      file_pipeline_proto_msgTypes,
	}.Build()
	File_pipeline_proto = out.File
	file_pipeline_proto_goTypes = nil
	file_pipeline_proto_depIdxs = nil
}
