// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: pipeline.proto

package pipeline

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PipelineService_Connect_FullMethodName       = "/yachiyo.pipeline.PipelineService/Connect"
	PipelineService_EventRegister_FullMethodName = "/yachiyo.pipeline.PipelineService/EventRegister"
	PipelineService_Publish_FullMethodName       = "/yachiyo.pipeline.PipelineService/Publish"
	PipelineService_Call_FullMethodName          = "/yachiyo.pipeline.PipelineService/Call"
)

// PipelineServiceClient is the client API for PipelineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PipelineServiceClient interface {
	// For clients or adapters, which provides a nearly 168-bytes long pipe.
	// Anything uses it may should have ability to request and to process.
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConnectRequest, ConnectReply], error)
	// Register an object, or tool providing to use.
	EventRegister(ctx context.Context, in *EventRegisterRequest, opts ...grpc.CallOption) (*ResultMessage, error)
	// I publish, and I run without noticing anything.
	Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*ResultMessage, error)
	// I call for some functions' help.
	Call(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CallRequest, CallReply], error)
}

type pipelineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPipelineServiceClient(cc grpc.ClientConnInterface) PipelineServiceClient {
	return &pipelineServiceClient{cc}
}

func (c *pipelineServiceClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConnectRequest, ConnectReply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PipelineService_ServiceDesc.Streams[0], PipelineService_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ConnectRequest, ConnectReply]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PipelineService_ConnectClient = grpc.BidiStreamingClient[ConnectRequest, ConnectReply]

func (c *pipelineServiceClient) EventRegister(ctx context.Context, in *EventRegisterRequest, opts ...grpc.CallOption) (*ResultMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResultMessage)
	err := c.cc.Invoke(ctx, PipelineService_EventRegister_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pipelineServiceClient) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*ResultMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResultMessage)
	err := c.cc.Invoke(ctx, PipelineService_Publish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pipelineServiceClient) Call(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CallRequest, CallReply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PipelineService_ServiceDesc.Streams[1], PipelineService_Call_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CallRequest, CallReply]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PipelineService_CallClient = grpc.BidiStreamingClient[CallRequest, CallReply]

// PipelineServiceServer is the server API for PipelineService service.
// All implementations must embed UnimplementedPipelineServiceServer
// for forward compatibility.
type PipelineServiceServer interface {
	// For clients or adapters, which provides a nearly 168-bytes long pipe.
	// Anything uses it may should have ability to request and to process.
	Connect(grpc.BidiStreamingServer[ConnectRequest, ConnectReply]) error
	// Register an object, or tool providing to use.
	EventRegister(context.Context, *EventRegisterRequest) (*ResultMessage, error)
	// I publish, and I run without noticing anything.
	Publish(context.Context, *PublishRequest) (*ResultMessage, error)
	// I call for some functions' help.
	Call(grpc.BidiStreamingServer[CallRequest, CallReply]) error
	mustEmbedUnimplementedPipelineServiceServer()
}

// UnimplementedPipelineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPipelineServiceServer struct{}

func (UnimplementedPipelineServiceServer) Connect(grpc.BidiStreamingServer[ConnectRequest, ConnectReply]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedPipelineServiceServer) EventRegister(context.Context, *EventRegisterRequest) (*ResultMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method EventRegister not implemented")
}
func (UnimplementedPipelineServiceServer) Publish(context.Context, *PublishRequest) (*ResultMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedPipelineServiceServer) Call(grpc.BidiStreamingServer[CallRequest, CallReply]) error {
	return status.Error(codes.Unimplemented, "method Call not implemented")
}
func (UnimplementedPipelineServiceServer) mustEmbedUnimplementedPipelineServiceServer() {}
func (UnimplementedPipelineServiceServer) testEmbeddedByValue()                         {}

// UnsafePipelineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PipelineServiceServer will
// result in compilation errors.
type UnsafePipelineServiceServer interface {
	mustEmbedUnimplementedPipelineServiceServer()
}

func RegisterPipelineServiceServer(s grpc.ServiceRegistrar, srv PipelineServiceServer) {
	// If the following call panics, it indicates UnimplementedPipelineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PipelineService_ServiceDesc, srv)
}

func _PipelineService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PipelineServiceServer).Connect(&grpc.GenericServerStream[ConnectRequest, ConnectReply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PipelineService_ConnectServer = grpc.BidiStreamingServer[ConnectRequest, ConnectReply]

func _PipelineService_EventRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PipelineServiceServer).EventRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PipelineService_EventRegister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PipelineServiceServer).EventRegister(ctx, req.(*EventRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PipelineService_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PipelineServiceServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PipelineService_Publish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PipelineServiceServer).Publish(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PipelineService_Call_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PipelineServiceServer).Call(&grpc.GenericServerStream[CallRequest, CallReply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PipelineService_CallServer = grpc.BidiStreamingServer[CallRequest, CallReply]

// PipelineService_ServiceDesc is the grpc.ServiceDesc for PipelineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PipelineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "yachiyo.pipeline.PipelineService",
	HandlerType: (*PipelineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EventRegister",
			Handler:    _PipelineService_EventRegister_Handler,
		},
		{
			MethodName: "Publish",
			Handler:    _PipelineService_Publish_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _PipelineService_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Call",
			Handler:       _PipelineService_Call_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pipeline.proto",
}
